### ISSUE TITLE
How to use stompee in spring boot?

### ISSUE THREAD

**Issue by waitshang** [phillip-kruger/stompee#10]
It's runtime now.

**Comment by phillip-kruger** [comment]
Why do you want it compile ? (It compiles fine without that ?)  Also it's not runtime now, it's provided, and that should be the case. Javax is provided by the app server and lombok is not needed as it just generated code on compile.

Please explain the issue you are having.

**Comment by waitshang** [comment]
> Why do you want it compile ? (It compiles fine without that ?) Also it's not runtime now, it's provided, and that should be the case. Javax is provided by the app server and lombok is not needed as it just generated code on compile.
> 
> Please explain the issue you are having.

sorry, i have made mistake. Is it possible to apply stompee to spring boot? I have no idea to do.

**Comment by phillip-kruger** [comment]
Not sure about Spring boot, sorry. Try thorntail or payara micro
